from teltek.parameters._parameter import (
    Parameter,
    ParameterGroup,
    ParameterType,
    ValueMapping,
    ValueRange,
)

_GREEN_DRIVING = ParameterGroup(
    key="green_driving",
    name="Green driving",
    parameters=[
        Parameter(
            key="scenario_settings",
            id=11000,
            type=ParameterType.U8,
            default_value=0,
            value_range=ValueRange(0, 3),
            name="Scenario settings",
            value_map=[
                ValueMapping("DISABLE", 0, "Disable"),
                ValueMapping("LOW_PRIORITY", 1, "Low priority"),
                ValueMapping("HIGH_PRIORITY", 2, "High priority"),
                ValueMapping("PANIC_PRIORITY", 3, "Panic priority"),
            ],
        ),
        Parameter(
            key="max_acceleration",
            id=11004,
            type=ParameterType.DOUBLE,
            default_value=2.5,
            value_range=ValueRange(0.5, 10),
            name="Max acceleration",
        ),
        Parameter(
            key="max_braking",
            id=11005,
            type=ParameterType.DOUBLE,
            default_value=2.7,
            value_range=ValueRange(0.5, 10),
            name="Max braking",
        ),
        Parameter(
            key="max_cornering",
            id=11006,
            type=ParameterType.DOUBLE,
            default_value=3.4,
            value_range=ValueRange(0.5, 10),
            name="Max cornering",
        ),
        Parameter(
            key="source",
            id=11007,
            type=ParameterType.U8,
            default_value=0,
            value_range=ValueRange(0, 1),
            name="Source",
            value_map=[
                ValueMapping("GPS", 0, "GPS"),
                ValueMapping("ACCELEROMETER", 1, "Accelerometer"),
            ],
        ),
        Parameter(
            key="duration",
            id=11008,
            type=ParameterType.U8,
            default_value=0,
            value_range=ValueRange(0, 1),
            name="Duration",
        ),
        Parameter(
            key="output_control",
            id=11003,
            type=ParameterType.U8,
            default_value=0,
            value_range=ValueRange(0, 2),
            name="Output control",
            value_map=[
                ValueMapping("NONE", 0, "None"),
                ValueMapping("DOUT1", 1, "DOUT 1"),
                ValueMapping("DOUT2", 2, "DOUT 2"),
            ],
        ),
        Parameter(
            key="dout_on_duration",
            id=11001,
            type=ParameterType.I32,
            default_value=200,
            value_range=ValueRange(0, 2147483647),
            name="DOUT ON duration",
        ),
        Parameter(
            key="dout_off_duration",
            id=11002,
            type=ParameterType.I32,
            default_value=200,
            value_range=ValueRange(0, 2147483647),
            name="DOUT OFF duration",
        ),
        Parameter(
            key="send_sms_to",
            id=7034,
            type=ParameterType.U8,
            default_value=0,
            value_range=ValueRange(0, 10),
            name="Send SMS to",
        ),
        Parameter(
            key="sms_text",
            id=8034,
            type=ParameterType.STRING,
            default_value="Green Driving",
            value_range=ValueRange(0, 160),
            name="Sms text",
        ),
    ],
)

_OVERSPEEDING_SCENARIO = ParameterGroup(
    key="overspeeding_scenario",
    name="Overspeeding scenario",
    parameters=[
        Parameter(
            key="scenario_settings",
            id=11100,
            type=ParameterType.U8,
            default_value=0,
            value_range=ValueRange(0, 3),
            name="Scenario settings",
            value_map=[
                ValueMapping("DISABLE", 0, "Disable"),
                ValueMapping("LOW_PRIORITY", 1, "Low priority"),
                ValueMapping("HIGH_PRIORITY", 2, "High priority"),
                ValueMapping("PANIC_PRIORITY", 3, "Panic priority"),
            ],
        ),
        Parameter(
            key="max_speed",
            id=11104,
            type=ParameterType.U16,
            default_value=90,
            value_range=ValueRange(0, 260),
            name="Max speed",
        ),
        Parameter(
            key="output_control",
            id=11103,
            type=ParameterType.U8,
            default_value=0,
            value_range=ValueRange(0, 2),
            name="Output control",
            value_map=[
                ValueMapping("NONE", 0, "None"),
                ValueMapping("DOUT1", 1, "DOUT 1"),
                ValueMapping("DOUT2", 2, "DOUT 2"),
            ],
        ),
        Parameter(
            key="dout_on_duration",
            id=11101,
            type=ParameterType.I32,
            default_value=200,
            value_range=ValueRange(0, 2147483647),
            name="DOUT ON duration",
        ),
        Parameter(
            key="dout_off_duration",
            id=11102,
            type=ParameterType.I32,
            default_value=200,
            value_range=ValueRange(0, 2147483647),
            name="DOUT OFF duration",
        ),
        Parameter(
            key="send_sms_to",
            id=7032,
            type=ParameterType.U8,
            default_value=0,
            value_range=ValueRange(0, 10),
            name="Send SMS to",
        ),
        Parameter(
            key="sms_text",
            id=8032,
            type=ParameterType.STRING,
            default_value="Overspeeding",
            value_range=ValueRange(0, 160),
            name="Sms text",
        ),
    ],
)

_JAMMING_SCENARIO = ParameterGroup(
    key="jamming_scenario",
    name="Jamming scenario",
    parameters=[
        Parameter(
            key="scenario_settings",
            id=11300,
            type=ParameterType.U8,
            default_value=0,
            value_range=ValueRange(0, 3),
            name="Scenario settings",
            value_map=[
                ValueMapping("DISABLE", 0, "Disable"),
                ValueMapping("LOW_PRIORITY", 1, "Low priority"),
                ValueMapping("HIGH_PRIORITY", 2, "High priority"),
                ValueMapping("PANIC_PRIORITY", 3, "Panic priority"),
            ],
        ),
        Parameter(
            key="eventual_records",
            id=11303,
            type=ParameterType.U8,
            default_value=1,
            value_range=ValueRange(0, 1),
            name="Eventual records",
            value_map=[
                ValueMapping("DISABLE", 0, "Disable"),
                ValueMapping("ENABLE", 1, "Enable"),
            ],
        ),
        Parameter(
            key="output_control",
            id=11304,
            type=ParameterType.U8,
            default_value=0,
            value_range=ValueRange(0, 2),
            name="Output control",
            value_map=[
                ValueMapping("NONE", 0, "None"),
                ValueMapping("DOUT1", 1, "DOUT1"),
                ValueMapping("DOUT2", 2, "DOUT2"),
            ],
        ),
        Parameter(
            key="dout_on_duration",
            id=11301,
            type=ParameterType.I32,
            default_value=200,
            value_range=ValueRange(0, 2147483647),
            name="DOUT ON duration",
        ),
        Parameter(
            key="dout_off_duration",
            id=11302,
            type=ParameterType.I32,
            default_value=200,
            value_range=ValueRange(0, 2147483647),
            name="DOUT OFF duration",
        ),
        Parameter(
            key="timeout",
            id=11305,
            type=ParameterType.U16,
            default_value=60,
            value_range=ValueRange(0, 65535),
            name="Timeout",
        ),
    ],
)

FEATURES = ParameterGroup(
    key="features",
    name="Features",
    groups=[
        _GREEN_DRIVING,
        _OVERSPEEDING_SCENARIO,
        _JAMMING_SCENARIO,
    ],
)
