from teltek.parameters._parameter import (
    Parameter,
    ParameterGroup,
    ParameterType,
    ValueMapping,
    ValueRange,
)

_PARAMETERS: list[Parameter] = [
    Parameter(
        key="brake_switch",
        id=79,
        type=ParameterType.U8,
        default_value=None,
        value_range=ValueRange(0, 1),
        name="Brake Switch",
        value_map=[
            ValueMapping("PEDAL_RELEASED", 0, "Pedal released"),
            ValueMapping("PEDAL_PRESSED", 1, "Pedal pressed"),
        ],
    ),
    Parameter(
        key="wheel_based_speed",
        id=80,
        type=ParameterType.U32,
        default_value=None,
        value_range=ValueRange(0, 65536),
        name="Wheel Based Speed",
    ),
    Parameter(
        key="cruise_control_active",
        id=81,
        type=ParameterType.U8,
        default_value=None,
        value_range=ValueRange(0, 1),
        name="Cruise Control Active",
        value_map=[
            ValueMapping("SWITCHED_OFF", 0, "Switched off"),
            ValueMapping("SWITCHED_ON", 1, "Switched on"),
        ],
    ),
    Parameter(
        key="clutch_switch",
        id=82,
        type=ParameterType.U8,
        default_value=None,
        value_range=ValueRange(0, 1),
        name="Clutch Switch",
        value_map=[
            ValueMapping("PEDAL_RELEASED", 0, "Pedal released"),
            ValueMapping("PEDAL_PRESSED", 1, "Pedal pressed"),
        ],
    ),
    Parameter(
        key="pto_state",
        id=83,
        type=ParameterType.U8,
        default_value=None,
        value_range=ValueRange(0, 1),
        name="PTO State",
        value_map=[
            ValueMapping("OFF_DISABLED", 0, "Off/disabled"),
            ValueMapping("SET", 1, "Set"),
            ValueMapping("NOT_AVAILABLE", 2, "Not available"),
        ],
    ),
    Parameter(
        key="acceleration_pedal_position",
        id=84,
        type=ParameterType.U32,
        default_value=None,
        value_range=ValueRange(0, 102),
        name="Acceleration Pedal Position",
    ),
    Parameter(
        key="engine_current_load",
        id=85,
        type=ParameterType.U8,
        default_value=None,
        value_range=ValueRange(0, 125),
        name="Engine Current Load",
    ),
    Parameter(
        key="engine_total_fuel_used",
        id=86,
        type=ParameterType.U32,
        default_value=None,
        value_range=ValueRange(0, 2105540607),
        name="Engine Total Fuel Used",
    ),
    Parameter(
        key="fuel_level",
        id=87,
        type=ParameterType.U32,
        default_value=None,
        value_range=ValueRange(0, 102),
        name="Fuel Level",
    ),
    Parameter(
        key="engine_speed",
        id=88,
        type=ParameterType.U32,
        default_value=None,
        value_range=ValueRange(0, 8032),
        name="Engine Speed",
    ),
    Parameter(
        key="axle_weight_1",
        id=89,
        type=ParameterType.U16,
        default_value=None,
        value_range=ValueRange(0, 32766),
        name="Axle Weight 1",
    ),
    Parameter(
        key="axle_weight_2",
        id=90,
        type=ParameterType.U16,
        default_value=None,
        value_range=ValueRange(0, 32766),
        name="Axle Weight 2",
    ),
    Parameter(
        key="axle_weight_3",
        id=91,
        type=ParameterType.U16,
        default_value=None,
        value_range=ValueRange(0, 32766),
        name="Axle Weight 3",
    ),
    Parameter(
        key="axle_weight_4",
        id=92,
        type=ParameterType.U16,
        default_value=None,
        value_range=ValueRange(0, 32766),
        name="Axle Weight 4",
    ),
    Parameter(
        key="axle_weight_5",
        id=93,
        type=ParameterType.U16,
        default_value=None,
        value_range=ValueRange(0, 32766),
        name="Axle Weight 5",
    ),
    Parameter(
        key="axle_weight_6",
        id=94,
        type=ParameterType.U16,
        default_value=None,
        value_range=ValueRange(0, 32766),
        name="Axle Weight 6",
    ),
    Parameter(
        key="axle_weight_7",
        id=95,
        type=ParameterType.U16,
        default_value=None,
        value_range=ValueRange(0, 32766),
        name="Axle Weight 7",
    ),
    Parameter(
        key="axle_weight_8",
        id=96,
        type=ParameterType.U16,
        default_value=None,
        value_range=ValueRange(0, 32766),
        name="Axle Weight 8",
    ),
    Parameter(
        key="axle_weight_9",
        id=97,
        type=ParameterType.U16,
        default_value=None,
        value_range=ValueRange(0, 32766),
        name="Axle Weight 9",
    ),
    Parameter(
        key="axle_weight_10",
        id=98,
        type=ParameterType.U16,
        default_value=None,
        value_range=ValueRange(0, 32766),
        name="Axle Weight 10",
    ),
    Parameter(
        key="axle_weight_11",
        id=99,
        type=ParameterType.U16,
        default_value=None,
        value_range=ValueRange(0, 32766),
        name="Axle Weight 11",
    ),
    Parameter(
        key="axle_weight_12",
        id=100,
        type=ParameterType.U16,
        default_value=None,
        value_range=ValueRange(0, 32766),
        name="Axle Weight 12",
    ),
    Parameter(
        key="axle_weight_13",
        id=101,
        type=ParameterType.U16,
        default_value=None,
        value_range=ValueRange(0, 32766),
        name="Axle Weight 13",
    ),
    Parameter(
        key="axle_weight_14",
        id=102,
        type=ParameterType.U16,
        default_value=None,
        value_range=ValueRange(0, 32766),
        name="Axle Weight 14",
    ),
    Parameter(
        key="axle_weight_15",
        id=103,
        type=ParameterType.U16,
        default_value=None,
        value_range=ValueRange(0, 32766),
        name="Axle Weight 15",
    ),
    Parameter(
        key="engine_total_hours_of_operation",
        id=104,
        type=ParameterType.U32,
        default_value=None,
        value_range=ValueRange(0, 214748364),
        name="Engine Total Hours Of Operation",
    ),
    Parameter(
        key="software_version_supported",
        id=109,
        type=ParameterType.U32,
        default_value=None,
        value_range=ValueRange(0, 0xFFFFFFFF),
        name="Software Version Supported",
    ),
    Parameter(
        key="diagnostics_supported",
        id=110,
        type=ParameterType.U8,
        default_value=None,
        value_range=ValueRange(0, 3),
        name="Diagnostics Supported",
    ),
    Parameter(
        key="requests_supported",
        id=111,
        type=ParameterType.U8,
        default_value=None,
        value_range=ValueRange(0, 3),
        name="Requests Supported",
    ),
    Parameter(
        key="service_distance",
        id=113,
        type=ParameterType.I32,
        default_value=None,
        value_range=ValueRange(-160635, 167040),
        name="Service Distance",
    ),
    Parameter(
        key="direction_indication",
        id=122,
        type=ParameterType.U8,
        default_value=None,
        value_range=ValueRange(0, 3),
        name="Direction Indication",
    ),
    Parameter(
        key="tachograph_performance",
        id=123,
        type=ParameterType.U8,
        default_value=None,
        value_range=ValueRange(0, 3),
        name="Tachograph Performance",
    ),
    Parameter(
        key="handling_info",
        id=124,
        type=ParameterType.U8,
        default_value=None,
        value_range=ValueRange(0, 3),
        name="Handling Info",
    ),
    Parameter(
        key="system_event",
        id=125,
        type=ParameterType.U8,
        default_value=None,
        value_range=ValueRange(0, 3),
        name="System Event",
    ),
    Parameter(
        key="engine_coolant_temperature",
        id=127,
        type=ParameterType.I8,
        default_value=None,
        value_range=ValueRange(-40, 210),
        name="Engine Coolant Temperature",
    ),
    Parameter(
        key="ambient_air_temperature",
        id=128,
        type=ParameterType.I16,
        default_value=None,
        value_range=ValueRange(-273, 1770),
        name="Ambient Air Temperature",
    ),
    Parameter(
        key="fuel_rate",
        id=135,
        type=ParameterType.U32,
        default_value=None,
        value_range=ValueRange(0, 3212),
        name="Fuel Rate",
    ),
    Parameter(
        key="instantaneous_fuel_economy",
        id=136,
        type=ParameterType.U32,
        default_value=None,
        value_range=ValueRange(0, 125),
        name="Instantaneous Fuel Economy",
    ),
    Parameter(
        key="pto_drive_engagement",
        id=137,
        type=ParameterType.U8,
        default_value=None,
        value_range=ValueRange(0, 3),
        name="PTO Drive Engagement",
    ),
    Parameter(
        key="high_resolution_engine_total_fuel_used",
        id=138,
        type=ParameterType.U32,
        default_value=None,
        value_range=ValueRange(0, 4211081.215),
        name="High Resolution Engine Total Fuel Used",
    ),
    Parameter(
        key="gross_combination_vehicle_weight",
        id=139,
        type=ParameterType.U32,
        default_value=None,
        value_range=ValueRange(0, 642550),
        name="Gross Combination Vehicle Weight",
    ),
    Parameter(
        key="adblue_status",
        id=229,
        type=ParameterType.U8,
        default_value=None,
        value_range=ValueRange(0, 3),
        name="AdBlue Status",
        value_map=[
            ValueMapping("OFF", 0, "Off"),
            ValueMapping("COND_RED", 1, "Cond. Red"),
            ValueMapping("COND_YELLOW", 2, "Cond. Yellow"),
            ValueMapping("COND_INFO", 3, "Cond. info"),
        ],
    ),
    Parameter(
        key="brake_pedal_position",
        id=357,
        type=ParameterType.U8,
        default_value=None,
        value_range=ValueRange(0, 100),
        name="Brake Pedal Position",
    ),
    Parameter(
        key="fuel_level_2",
        id=10348,
        type=ParameterType.U8,
        default_value=None,
        value_range=ValueRange(0, 100),
        name="Fuel Level 2",
    ),
    Parameter(
        key="mil_indicator",
        id=10349,
        type=ParameterType.U8,
        default_value=None,
        value_range=ValueRange(0, 100),
        name="MIL Indicator",
        value_map=[
            ValueMapping("OFF", 0, "OFF"),
            ValueMapping("COND_RED", 1, "Condition Red"),
            ValueMapping("COND_YELLOW", 2, "Condition Yellow"),
            ValueMapping("COND_INFO", 3, "Condition Info"),
            ValueMapping("NOT_AVAILABLE", 7, "Not Available"),
        ],
    ),
    Parameter(
        key="tell_tale_0",
        id=10428,
        type=ParameterType.U64,
        default_value=None,
        value_range=ValueRange(0, 0xFFFFFFFFFFFFFFFF),
        name="Tell Tale 0",
    ),
    Parameter(
        key="tell_tale_1",
        id=10429,
        type=ParameterType.U64,
        default_value=None,
        value_range=ValueRange(0, 0xFFFFFFFFFFFFFFFF),
        name="Tell Tale 1",
    ),
    Parameter(
        key="tell_tale_2",
        id=10430,
        type=ParameterType.U64,
        default_value=None,
        value_range=ValueRange(0, 0xFFFFFFFFFFFFFFFF),
        name="Tell Tale 2",
    ),
    Parameter(
        key="tell_tale_3",
        id=10431,
        type=ParameterType.U64,
        default_value=None,
        value_range=ValueRange(0, 0xFFFFFFFFFFFFFFFF),
        name="Tell Tale 3",
    ),
    Parameter(
        key="adblue_level",
        id=10455,
        type=ParameterType.U8,
        default_value=None,
        value_range=ValueRange(0, 100),
        name="AdBlue Level",
    ),
    Parameter(
        key="dtc_dm1",
        id=10493,
        type=ParameterType.U32,
        default_value=None,
        value_range=ValueRange(0, 4294967295),
        name="DTC DM1",
    ),
    Parameter(
        key="dtc_time_dm1",
        id=10494,
        type=ParameterType.U32,
        default_value=None,
        value_range=ValueRange(0, 4294967295),
        name="DTC Time DM1",
    ),
    Parameter(
        key="dtc_dm2",
        id=10495,
        type=ParameterType.U32,
        default_value=None,
        value_range=ValueRange(0, 4294967295),
        name="DTC DM2",
    ),
    Parameter(
        key="dtc_time_dm2",
        id=10496,
        type=ParameterType.U32,
        default_value=None,
        value_range=ValueRange(0, 4294967295),
        name="DTC Time DM2",
    ),
]

# TODO appears to be FMC650 exclusive?
FMS = ParameterGroup(
    key="fms",
    name="FMS",
    parameters=_PARAMETERS,
)
